import "../styles/globals.css";

import Head from "next/head";
import type { AppProps } from "next/app";
import { Provider } from "react-redux";

import { store } from "../app/store";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Belajar redux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Provider store={store}>
        <Component {...pageProps} />
      </Provider>
    </>
  );
}

export default MyApp;
